% Testing the effectiveness of unconventional monetary policy in Japan and the United States
% Daisuke Ikeda, Shangshang Li, Sophocles Mavroeidis, and Francesco Zanetti
% American Economic Journal: Macroeconomics

% This code generates Figure 2 in the main text.
% This code computes impulse responses under Proposition 2 for different
% effectiveness of UMP (lambdas = 0, 0.5, or 1 in line 12 below).

clear
close all

lambdas = 0;      % = 0, 0.5, or 1 (effectiveness of UMP)

option = 1;       % 0: compute IRFs under Proposition 2 and save results
                  % 1: read saved IRFs and plot figures
                  
if option == 0
    
    % Construct matrices in the form of equation (41) of Mavroeidis (2021)
    if lambdas == 0     % generated by run_zlb.m (lambdas_p A11 A12 A12s B11 B11s A22s A22 A21 B21 B21s b iU_ss piU_ss yU_ss)
        load var_matrices_lambdas0
    elseif lambdas == 0.5
        load var_matrices_lambdas05
    elseif lambdas == 1
        load var_matrices_lambdas1
    end
    
    if lambdas == 0
        load IRFlambda0
    elseif lambdas == 0.5
        load IRFlambda05
    elseif lambdas == 1
        load IRFlambda1
    end
    
    Ab = [A11 A12+A12s; A21 A22+A22s];
    As = [A11 A12s; A21 A22s];
    B = [B11;B21];
    Bs = [B11s; B21s];
    
    % Variables: Ys = [Y1' Y2s']' = [y pi is]'; X = Y(t-1); Y = [Y1' Y2']' = [y pi i]'; Xs = Y2s(t-1) = is;
    %            eps = [supply, demand, monetary]';
    % Model: Ys = C*X + Cs*Xs + G*eps if D=0 (non-ZLB)
    %           = Ct*X + Cts*Xs + ct + Gt*eps (ZLB)
    
    G = inv(Ab);
    C = G*B;
    Cs = G*Bs;
    
    Gt = inv(As);
    Ct = Gt*B;
    Cts = Gt*Bs;
    ct = - Gt*[A12;A22].*b;
    
   % (Stochastic) Impulse responses
    T = 30;                        % IRF horizon
    N = 1000;                      % number of simulations
    IRF = zeros(T,N,4);            % IRF with monetary policy shock in t=2
    IRF0 = zeros(T,N,4);           % IRF with no monetary policy shock in t=2
    E = zeros(3,T,N);
    rng(1)
    E(:,2:end,:) = randn(3,T-1,N); % shocks with monetary policy shock in t=2
    E0 = E;                        % shocks with no monetary policy shock in t=2
    E(3,2,:) = -1;                 % standard deviation of the monetary policy shock in t=2
    E0(3,2,:) = 0;                 % no monetary policy shock in t=2
    X_0 = [IRF_init(1,1,3)/100 IRF_init(1,1,2)/400 IRF_init(1,1,1)/400/(1+iU_ss)]'; % initial condition [y pi i]
    Xs_0 = IRF_init(1,1,4)/400/(1+iU_ss);                                       % initial condition iT
    
    paramfile_model
    IRF(1,:,1) = IRF_init(1,1,1);      % interest rate
    IRF(1,:,2) = IRF_init(1,1,2);      % inflation
    IRF(1,:,3) = IRF_init(1,1,3);      % output
    IRF(1,:,4) = IRF_init(1,1,4);      % Taylor rule rate
    IRF0(1,:,1) = IRF_init(1,1,1);     % interest rate, no monetary policy shock
    IRF0(1,:,2) = IRF_init(1,1,2);     % inflation, no monetary policy shock
    IRF0(1,:,3) = IRF_init(1,1,3);     % output, no monetary policy shock
    IRF0(1,:,4) = IRF_init(1,1,4);     % Taylor rule rate, no monetary policy shock
    SD = diag([siga_p sigb_p sigi_p]);
    
    % Save shocks
    Esave = zeros(T*N,4);
    tt=1:1:T; tt=tt';
    for n=1:N
        Eps0 = SD*E0(:,:,n);
        Esave(1+(n-1)*T:n*T,:)=[tt Eps0'];
    end
    
    h = timebar('Loop counter','Progress');
    tic;
    for n=1:N
        Eps = SD*E(:,:,n);
        Eps0 = SD*E0(:,:,n);
        X = X_0;  Xs = Xs_0;   % initial condition = steady state
        X0 = X_0; Xs0 = Xs_0;  % initial condition = steady state
        for t=2:T
            Ys = C*X + Cs*Xs + G*Eps(:,t);
            Ys0 = C*X0 + Cs*Xs0 + G*Eps0(:,t);
            if Ys(3) < b
                Ys = Ct*X + Cts*Xs + ct + Gt*Eps(:,t);
            end
            X = [Ys(1);Ys(2);max(Ys(3),b)];
            Xs = Ys(3);
            if Ys0(3) < b
                Ys0 = Ct*X0 + Cts*Xs0 + ct + Gt*Eps0(:,t);
            end
            X0 = [Ys0(1);Ys0(2);max(Ys0(3),b)];
            Xs0 = Ys0(3);
            % IRF
            IRF(t,n,1) = max(Ys(3),b)*400*(1+iU_ss);    % interest rate
            IRF(t,n,2) = Ys(2)*400;                     % inflation
            IRF(t,n,3) = Ys(1)/yU_ss*100;               % output
            IRF(t,n,4) = Ys(3)*400*(1+iU_ss);           % Taylor rule rate
            IRF0(t,n,1) = max(Ys0(3),b)*400*(1+iU_ss);  % interest rate, no monetary policy shock
            IRF0(t,n,2) = Ys0(2)*400;                   % inflation, no monetary policy shock
            IRF0(t,n,3) = Ys0(1)/yU_ss*100;             % output, no monetary policy shock
            IRF0(t,n,4) = Ys0(3)*400*(1+iU_ss);         % Taylor rule rate, no monetary policy shoc
        end
        timebar(h,n/N)
    end
    close(h)
    toc
    
    % IRFs
    IRFm = zeros(T,3);
    for j=1:3
        IRFm(:,j) = mean(IRF(:,:,j),2) - mean(IRF0(:,:,j),2);
    end
    
    % Save the result
    if lambdas == 0
        save IRFlambda0_prop2 IRFm
    elseif lambdas == 0.5
        save IRFlambda05_prop2 IRFm
    elseif lambdas == 1
        save IRFlambda1_prop2 IRFm
    end
    
else
    
    load IRFlambda0
    IRFm_lam0_ob=IRFm_ob;
    load IRFlambda0_prop2
    IRFm_lam0_prop2=IRFm;
    
    load IRFlambda05
    IRFm_lam05_ob=IRFm_ob;
    load IRFlambda05_prop2
    IRFm_lam05_prop2=IRFm;
    
    load IRFlambda1
    IRFm_lam1_ob=IRFm_ob;
    load IRFlambda1_prop2
    IRFm_lam1_prop2=IRFm;
    
    tt=1:1:15;
    fsize = 13;
    fsize2 = 12;
    figure('name','Figure 2: Impulse responses to a monetary policy shock at the ELB')
    subplot(3,3,1)
    plot(tt,IRFm_lam0_prop2(tt,1),'-b',tt,IRFm_lam0_ob(tt,1),'--r','linewidth',2)
    str_t = 'Interest rate $$i_{t}$$ (pts)';
    title(str_t,'Interpreter','latex','Fontsize',fsize)
    str_y = '$$\xi=0$$';
    ylabel(str_y,'Interpreter','latex','Fontsize',fsize)
    leg = legend('Proposition 2','OccBin','Fontsize',fsize2);
    set(leg,'Interpreter','latex');
    ylim([-0.15,0])
    
    subplot(3,3,2)
    plot(tt,IRFm_lam0_prop2(tt,3),'-b',tt,IRFm_lam0_ob(tt,3),'--r','linewidth',2)
    str_t = 'Output $$y_{t}$$ (\%)';
    title(str_t,'Interpreter','latex','Fontsize',fsize)
    ylim([0,0.06])
    
    subplot(3,3,3)
    plot(tt,IRFm_lam0_prop2(tt,2),'-b',tt,IRFm_lam0_ob(tt,2),'--r','linewidth',2)
    str_t = 'Inflation $$\pi_{t}$$ (pts)';
    title(str_t,'Interpreter','latex','Fontsize',fsize)
    ylim([0,0.15])
    
    subplot(3,3,4)
    plot(tt,IRFm_lam05_prop2(tt,1),'-b',tt,IRFm_lam05_ob(tt,1),'--r','linewidth',2)
    str_y = '$$\xi=0.5$$';
    ylabel(str_y,'Interpreter','latex','Fontsize',fsize)
    ylim([-0.15,0])
    
    subplot(3,3,5)
    plot(tt,IRFm_lam05_prop2(tt,3),'-b',tt,IRFm_lam05_ob(tt,3),'--r','linewidth',2)
    ylim([0,0.06])
    
    subplot(3,3,6)
    plot(tt,IRFm_lam05_prop2(tt,2),'-b',tt,IRFm_lam05_ob(tt,2),'--r','linewidth',2)
    ylim([0,0.15])
    
    subplot(3,3,7)
    plot(tt,IRFm_lam1_prop2(tt,1),'-b',tt,IRFm_lam1_ob(tt,1),'--r','linewidth',2)
    str_y = '$$\xi=1$$';
    ylabel(str_y,'Interpreter','latex','Fontsize',fsize)
    ylim([-0.15,0])
    
    subplot(3,3,8)
    plot(tt,IRFm_lam1_prop2(tt,3),'-b',tt,IRFm_lam1_ob(tt,3),'--r','linewidth',2)
    ylim([0,0.06])
    
    subplot(3,3,9)
    plot(tt,IRFm_lam1_prop2(tt,2),'-b',tt,IRFm_lam1_ob(tt,2),'--r','linewidth',2)
    ylim([0,0.15])
end
