% Testing the effectiveness of unconventional monetary policy in Japan and the United States
% Daisuke Ikeda, Shangshang Li, Sophocles Mavroeidis, and Francesco Zanetti
% American Economic Journal: Macroeconomics

% This code generates Figures 1 and 2 in Online Appendix.
% For Figure 1, set "shock = 1" in line 17 below.
% For Figure 2, set "schok = 2" in line 17 below.

clear
close all

option = 1;         % 0: compute IRFs
                    % 1: use saved data

lambdas = 1;        % = 0, 0.5, or 1 (effectiveness of UMP)

shock = 2;          % 1: demand shock
                    % 2: supply shock
                    
if option == 0
    
    % Construct matrices in the form of equation (41) of Mavroeidis (2021)
    if lambdas == 0     % generated by run_zlb.m (lambdas_p A11 A12 A12s B11 B11s A22s A22 A21 B21 B21s b iU_ss piU_ss yU_ss)
        load var_matrices_lambdas0
    elseif lambdas == 0.5
        load var_matrices_lambdas05
    elseif lambdas == 1
        load var_matrices_lambdas1
    end
   
    Ab = [A11 A12+A12s; A21 A22+A22s];
    As = [A11 A12s; A21 A22s];
    B = [B11;B21];
    Bs = [B11s; B21s];
    
    % Variables: Ys = [Y1' Y2s']' = [y pi is]'; X = Y(t-1); Y = [Y1' Y2']' = [y pi i]'; Xs = Y2s(t-1) = is;
    %            eps = [supply, demand, monetary]';
    % Model: Ys = C*X + Cs*Xs + G*eps if D=0 (non-ZLB)
    %           = Ct*X + Cts*Xs + ct + Gt*eps (ZLB)
    
    G = inv(Ab);
    C = G*B;
    Cs = G*Bs;
    
    Gt = inv(As);
    Ct = Gt*B;
    Cts = Gt*Bs;
    ct = - Gt*[A12;A22].*b;
    
   % Load the IRFs obtained by using OccBin for getting an initial condition
    if lambdas == 0
        load IRFlambda0
    elseif lambdas == 0.5
        load IRFlambda05
    elseif lambdas == 1
        load IRFlambda1
    end
    
   % Initial condition
    X_0 = [IRF_init(1,1,3)/100 IRF_init(1,1,2)/400 IRF_init(1,1,1)/400/(1+iU_ss)]'; % initial condition [y pi i]
    Xs_0 = IRF_init(1,1,4)/400/(1+iU_ss);                                       % initial condition iT
    
   % (Stochastic) Impulse responses
    T = 30;                        % IRF horizon
    N = 1000;                      % number of simulations
    IRF = zeros(T,N+1,4);          % IRF with shock in t=2
    IRF0 = zeros(T,N+1,4);         % IRF with no shock in t=2
    E = zeros(3,T,N+1);
    rng(1)
    E(:,2:end,1:N) = randn(3,T-1,N); % shocks with a shock in t=2
    E0 = E;                          % shocks with no shock in t=2
    if shock == 1
        E(2,2,:) = 1;          % demand shock
        E0(2,2,:) = 0;         % no shock in t=2
    elseif shock == 2
        E(1,2,:) = -1;         % supply shock
        E0(1,2,:) = 0;         % no shock in t=2 
    end
    
    paramfile_model
    IRF(1,:,1) = IRF_init(1,1,1);      % interest rate
    IRF(1,:,2) = IRF_init(1,1,2);      % inflation
    IRF(1,:,3) = IRF_init(1,1,3);      % output
    IRF(1,:,4) = IRF_init(1,1,4);      % Taylor rule rate
    IRF0(1,:,1) = IRF_init(1,1,1);     % interest rate, no monetary policy shock
    IRF0(1,:,2) = IRF_init(1,1,2);     % inflation, no monetary policy shock
    IRF0(1,:,3) = IRF_init(1,1,3);     % output, no monetary policy shock
    IRF0(1,:,4) = IRF_init(1,1,4);     % Taylor rule rate, no monetary policy shock
    SD = diag([siga_p sigb_p sigi_p]);
    
    % Save shocks
    Esave = zeros(T*N,4);
    tt=1:1:T; tt=tt';
    for n=1:N+1
        Eps0 = SD*E0(:,:,n);
        Esave(1+(n-1)*T:n*T,:)=[tt Eps0'];
    end
    
    h = timebar('Loop counter','Progress');
    tic;
    for n=1:N+1
        Eps = SD*E(:,:,n);
        Eps0 = SD*E0(:,:,n);
        X = X_0;  Xs = Xs_0;   % initial condition = steady state
        X0 = X_0; Xs0 = Xs_0;  % initial condition = steady state
        for t=2:T
            Ys = C*X + Cs*Xs + G*Eps(:,t);
            Ys0 = C*X0 + Cs*Xs0 + G*Eps0(:,t);
            if Ys(3) < b
                Ys = Ct*X + Cts*Xs + ct + Gt*Eps(:,t);
            end
            X = [Ys(1);Ys(2);max(Ys(3),b)];
            Xs = Ys(3);
            if Ys0(3) < b
                Ys0 = Ct*X0 + Cts*Xs0 + ct + Gt*Eps0(:,t);
            end
            X0 = [Ys0(1);Ys0(2);max(Ys0(3),b)];
            Xs0 = Ys0(3);
            % IRF
            IRF(t,n,1) = max(Ys(3),b)*400*(1+iU_ss);    % interest rate
            IRF(t,n,2) = Ys(2)*400;                     % inflation
            IRF(t,n,3) = Ys(1)/yU_ss*100;               % output
            IRF(t,n,4) = Ys(3)*400*(1+iU_ss);           % Taylor rule rate
            IRF0(t,n,1) = max(Ys0(3),b)*400*(1+iU_ss);  % interest rate, no monetary policy shock
            IRF0(t,n,2) = Ys0(2)*400;                   % inflation, no monetary policy shock
            IRF0(t,n,3) = Ys0(1)/yU_ss*100;             % output, no monetary policy shock
            IRF0(t,n,4) = Ys0(3)*400*(1+iU_ss);         % Taylor rule rate, no monetary policy shock
        end
        timebar(h,n/(N+1))
    end
    close(h)
    toc
    
    % IRFs
    IRFm = zeros(T,3);
    IRFn = zeros(T,3);
    for j=1:3
        IRFm(:,j) = mean(IRF(:,1:N,j),2) - mean(IRF0(:,1:N,j),2);
        IRFn(:,j) = IRF(:,N+1,j) - IRF0(:,N+1,j);
    end
    
    % Save and plot figures
    if shock == 1
        if lambdas == 0
            save IRFlambda0_prop2_d IRFm
        elseif lambdas == 0.5
            save IRFlambda05_prop2_d IRFm
        elseif lambdas == 1
            save IRFlambda1_prop2_d IRFm
        end
    elseif shock == 2
        if lambdas == 0
            save IRFlambda0_prop2_a IRFm
        elseif lambdas == 0.5
            save IRFlambda05_prop2_a IRFm
        elseif lambdas == 1
            save IRFlambda1_prop2_a IRFm
        end
    end
       
else 
    tt=1:1:15;
    fsize=13;
    fsize2=12;
    if shock == 1
        
        load IRFlambda0_prop2_d
        IRFm_lam0_d=IRFm;
        load IRFlambda05_prop2_d
        IRFm_lam05_d=IRFm;
        load IRFlambda1_prop2_d
        IRFm_lam1_d=IRFm;
    
        figure('name','Figure 1 in Online Appendix: Impulse responses to a demand shock at the ELB')
        subplot(1,2,1)
        plot(tt,IRFm_lam0_d(tt,3),'-.c',tt,IRFm_lam05_d(tt,3),'--r',tt,IRFm_lam1_d(tt,3),'-b','linewidth',2)
        str_t = 'Output $$y_{t}$$ (\%)';
        title(str_t,'Interpreter','latex','Fontsize',fsize)
        leg = legend('$$\xi=0$$','$$\xi=0.5$$','$$\xi=1$$');
        set(leg,'Interpreter','latex','Fontsize',fsize2);

        subplot(1,2,2)
        plot(tt,IRFm_lam0_d(tt,2),'-.c',tt,IRFm_lam05_d(tt,2),'--r',tt,IRFm_lam1_d(tt,2),'-b','linewidth',2)
        str_t = 'Inflation $$\pi_{t}$$ (pts)';
        title(str_t,'Interpreter','latex','Fontsize',fsize)
            
    elseif shock == 2
    
        load IRFlambda0_prop2_a
        IRFm_lam0_a=IRFm;
        load IRFlambda05_prop2_a
        IRFm_lam05_a=IRFm;
        load IRFlambda1_prop2_a
        IRFm_lam1_a=IRFm;
        
        figure('name','Figure 2 in Online Appendix: Impulse responses to a supply shock at the ELB')
        subplot(1,2,1)
        plot(tt,IRFm_lam0_a(tt,3),'-.c',tt,IRFm_lam05_a(tt,3),'--r',tt,IRFm_lam1_a(tt,3),'-b','linewidth',2)
        str_t = 'Output $$y_{t}$$ (\%)';
        title(str_t,'Interpreter','latex','Fontsize',fsize)
        leg = legend('$$\xi=0$$','$$\xi=0.5$$','$$\xi=1$$');
        set(leg,'Interpreter','latex','Fontsize',fsize2);
        
        subplot(1,2,2)
        plot(tt,IRFm_lam0_a(tt,2),'-.c',tt,IRFm_lam05_a(tt,2),'--r',tt,IRFm_lam1_a(tt,2),'-b','linewidth',2)
        str_t = 'Inflation $$\pi_{t}$$ (pts)';
        title(str_t,'Interpreter','latex','Fontsize',fsize)
        
    end
end
