% Testing the effectiveness of unconventional monetary policy in Japan and the United States
% Daisuke Ikeda, Shangshang Li, Sophocles Mavroeidis, and Francesco Zanetti
% American Economic Journal: Macroeconomics

% This code generates Figure 1 in the main taxt.
% This code computes the dynamic paths of the economy under Proposition 2
% for effectiveness of UMP (lambdas = 0, 0.5, or 1 in line 12 below).

clear
close all

lambdas = 1;   % = 0, 0.5, or 1 (effectiveness of UMP)

pf = 0;        % 0: plot figures for the paper
               % 1: no figures for the paper

% Construct matrices in the form of equation (41) of Mavroeidis (2021)
if lambdas == 0     % generated by run_zlb.m (lambdas_p A11 A12 A12s B11 B11s A22s A22 A21 B21 B21s b iU_ss piU_ss yU_ss)
    load var_matrices_lambdas0
elseif lambdas == 0.5
    load var_matrices_lambdas05
elseif lambdas == 1
    load var_matrices_lambdas1
end

Ab = [A11 A12+A12s; A21 A22+A22s];
As = [A11 A12s; A21 A22s];
B = [B11;B21];
Bs = [B11s; B21s];

% Variables: Ys = [Y1' Y2s']' = [y pi is]'; X = Y(t-1); Y = [Y1' Y2']' = [y pi i]'; Xs = Y2s(t-1) = is;
%            eps = [supply, demand, monetary]';
% Model: Ys = C*X + Cs*Xs + G*eps if D=0 (non-ZLB)
%           = Ct*X + Cts*Xs + ct + Gt*eps (ZLB)

G = inv(Ab);
C = G*B;
Cs = G*Bs;

Gt = inv(As);
Ct = Gt*B;
Cts = Gt*Bs;
ct = - Gt*[A12;A22].*b;

% Shocks
paramfile_model
SD = diag([siga_p sigb_p sigi_p]);
E = [ zeros(5,3)
   0 5 0
   0 5 0
   zeros(23,3)]*SD;
E=E';

% IRFs
T = size(E,2);
IRFi_prop2 = zeros(T,2);    % i, i*
IRFy_prop2 = zeros(T,1);    % y
IRFpi_prop2 = zeros(T,1);   % pi

X = zeros(3,1);       % initial condition for [y pi i]
Xs = 0;               % initial condition for iT
for t=1:T  % Ys=[y pi iT]'; 
    Ys = C*X + Cs*Xs + G*E(:,t);
    if Ys(3) < b
        Ys = Ct*X + Cts*Xs + ct + Gt*E(:,t);
    end
    X = [Ys(1);Ys(2);max(Ys(3),b)];
    Xs = Ys(3);
    IRFi_prop2(t,1) = (X(3)+iU_ss)*400*(1+iU_ss);
    IRFi_prop2(t,2) = (Xs+iU_ss)*400*(1+iU_ss);
    IRFy_prop2(t) = X(1)/yU_ss*100;
    IRFpi_prop2(t) = X(2)*400; 
end

% Save IRFs
if lambdas==0
    save IRF_lambda0_prop2 IRFi_prop2 IRFy_prop2 IRFpi_prop2
elseif lambdas==0.5
    save IRF_lambda05_prop2 IRFi_prop2 IRFy_prop2 IRFpi_prop2
elseif lambdas==1
    save IRF_lambda1_prop2 IRFi_prop2 IRFy_prop2 IRFpi_prop2
end

% Plot figures for the paper
if pf == 0
   tt = 1:1:25;
   load IRF_lambda0_prop2
   IRFi0=IRFi_prop2; IRFy0=IRFy_prop2; IRFpi0=IRFpi_prop2;
   load IRF_lambda05_prop2
   IRFi05=IRFi_prop2; IRFy05=IRFy_prop2; IRFpi05=IRFpi_prop2;
   load IRF_lambda1_prop2
   IRFi1=IRFi_prop2; IRFy1=IRFy_prop2; IRFpi1=IRFpi_prop2;
   
   figure('name','Figure 1: The Effects of UMP')
   fsize=13;
   fsize2=12;
   subplot(1,3,1)
   plot(tt,IRFi0(tt,1),'-.c',tt,IRFi05(tt,1),'--r',tt,IRFi1(tt,1),'-b','linewidth',2)
   hold on
   plot(tt,IRFi1(tt,2),'-b*')
   str_t = 'Interest rate $$i_{t}$$ (\%, level)';
   title(str_t,'Interpreter','latex','Fontsize',fsize)
   leg = legend('$$\xi=0$$','$$\xi=0.5$$','$$\xi=1$$','No ZLB');
   set(leg,'Interpreter','latex','Fontsize',fsize2);
   
   subplot(1,3,2)
   plot(tt,IRFy0(tt,1),'-.c',tt,IRFy05(tt,1),'--r',tt,IRFy1(tt,1),'-b','linewidth',2)
   hold on
   plot(tt,IRFy1(tt,1),'-b*')
   str_t = 'Output $$y_{t}$$ (\% dev. from SS)';
   title(str_t,'Interpreter','latex','Fontsize',fsize)
   
   subplot(1,3,3)
   plot(tt,IRFpi0(tt,1),'-.c',tt,IRFpi05(tt,1),'--r',tt,IRFpi1(tt,1),'-b','linewidth',2)
   hold on
   plot(tt,IRFpi1(tt,1),'-b*')
   str_t = 'Inflation $$\pi_{t}$$ (\%, diff. from SS)';
   title(str_t,'Interpreter','latex','Fontsize',fsize)
   
end